image: mambaorg/micromamba

stages:
  - test

test:
  stage: test
  script:
    - micromamba create -n glaes --file=requirements-dev.yml
    - eval "$(micromamba shell hook --shell bash)"
    - micromamba activate glaes
    - pip install -e . --no-deps
    - pytest --cov=glaes glaes/test/


