image: continuumio/miniconda3:latest

stages:
  - test

test:
  stage: test
  tags: 
    - linux

  script: 
    - conda install mamba -c conda-forge
    - mamba env update -n glaes --file=requirements.yml
    - mamba env update -n glaes --file=requirements-dev.yml
    - mamba info --envs
    - source activate glaes
    - git clone https://CIGlaes:$GeokitAccessToken@jugit.fz-juelich.de/iek-3/shared-code/geokit.git
    - cd geokit
    - git checkout dev
    - python -m pip install -e .
    - cd ..
    - python -m pip install -e .
    - python -m pytest --cov=glaes glaes/test/
