image: mambaorg/micromamba

stages:
  - test

test-code:
  stage: test
  script:
    - micromamba create -n glaes --file=requirements-dev.yml
    - eval "$(micromamba shell hook --shell bash)"
    - micromamba activate glaes
    - pip install -e . --no-deps
    - pytest --cov=glaes glaes/test/

test-formatting:
  stage: test
  image: pyfound/black:latest_release
  script:
  # Dry-run black auto-formatter. If the code needs reformatting this test
  # will fail.
  - black --version
  - black --check glaes
  - black --check test
