image: continuumio/miniconda3:latest

stages:
  - test

test:
  stage: test
  tags: 
    - linux

  script:
    - echo "${Test}"
    - conda install mamba -c conda-forge
    - mamba create -n glaes
    - source activate glaes
    - git clone --branch dev https://CIGlaes:${GeokitAccessToken}@jugit.fz-juelich.de/iek-3/shared-code/geokit.git
    - cd geokit
    - mamba env update --file=requirements-dev.yml
    - python -m pip install -e .
    - cd ..
    - mamba env update --file=requirements-dev.yml
    - mamba info --envs
    - python -m pip install -e .
    - python -m pytest --cov=glaes glaes/test/
