image: continuumio/miniconda3:latest

stages:
  - test

test:
  stage: test
  tags: 
    - linux

  script:
    - conda install mamba -c conda-forge
    - mamba create -n glaes python=3.8
    - source activate glaes
    - git clone --branch dev https://CIGlaes:${GeokitAccessToken}@jugit.fz-juelich.de/iek-3/shared-code/geokit.git
    - cd geokit
    - mamba install -c conda-forge numpy, descartes, pandas, scipy, matplotlib
    - python -m pip install smopy
    - mamba install -c conda-forge gdal=2.4.4
    - python -m pip install -e .
    - cd ..
    - python -m pip show geokit
    - mamba env update -n glaes --file=requirements-dev.yml
    - python -m pytest --cov=glaes glaes/test/
