image: continuumio/miniconda3:latest

stages:
  - test

test:
  stage: test
  tags: 
    - linux

  script:
    - conda install mamba -c conda-forge
    - mamba create -n glaes
    - source activate glaes
    - mamba install -c conda-forge gdal=2.4.4
    - python -m pip show gdal
    - git clone --branch dev https://CIGlaes:${GeokitAccessToken}@jugit.fz-juelich.de/iek-3/shared-code/geokit.git
    - cd geokit
    - mamba env update -n glaes --file=requirements-dev.yml --freeze-installed
    - cd ..
    - python -m pip show geokit
    - mamba env update -n glaes --file=requirements-dev.yml
    - python -m pytest --cov=glaes glaes/test/
