name: glaes
channels:
  - conda-forge
dependencies:
  # - python
  # - pytest
  # - pytest-cov
  # - pylint
  # - autopep8
  # - jupyter
  # - notebook
  # - jupyterlab
  - conda-forge::pip
  - conda-forge::matplotlib
  - conda-forge::descartes
  - conda-forge::pandas
  - conda-forge::numpy<1.24
  - conda-forge::scipy
  - conda-forge::scikit-learn
  - conda-forge::geokit>=1.4.0
  - conda-forge::gdal=3.4.*
  - pip:
      - e .

