name: glaes
channels:
  - conda-forge
dependencies:
  # - python
  # - pytest
  # - pytest-cov
  # - pylint
  # - autopep8
  # - jupyter
  # - notebook
  # - jupyterlab
  - pip
  - matplotlib
  - descartes
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - geokit>=1.4.0
  - gdal=3.4.*
  - pip:
      - .

