name: glaes
channels:
  - conda-forge
dependencies:
  - conda-forge::pip
  - conda-forge::matplotlib
  - conda-forge::descartes
  - conda-forge::pandas
  - conda-forge::numpy<=1.24
  - conda-forge::scipy
  - conda-forge::scikit-learn
  - conda-forge::gdal>2.4,<=2.4.4
  - conda-forge::geokit=1.3.0
