name: glaes
channels:
  - conda-forge
dependencies:
  - conda-forge::pip
  - conda-forge::matplotlib
  - conda-forge::descartes
  - conda-forge::pandas
  - conda-forge::numpy<=1.23.1
  - conda-forge::scipy
  - conda-forge::scikit-learn
  - conda-forge::geokit>=1.3.0
  - conda-forge::gdal=3.4.*
