on:
    push:
        branches: ["**"]

defaults:
    run:
        shell: pwsh

jobs:
    run-conda-forge-test:
        name: "Run test for glaes on ${{ matrix.runner_tag }}"
        strategy:
            fail-fast: false
            matrix:
                runner_tag: ["ubuntu-latest"]
        runs-on: ${{ matrix.runner_tag }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  path: "glaes"
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  # Repository name with owner. For example, actions/checkout
                  repository: "FZJ-IEK3-VSA/geokit"
                  path: "geokit"
            - name: Show directory
              run: |
                  Get-ChildItem -Recurse
            - name: Merge yaml files
              id: get_username
              uses: mikefarah/yq@master
              with:
                  cmd: yq4 eval-all '. as $item ireduce ({}; . *+ $item)' geokit/requirements-dev.yml glaes/requirements-dev.yml > combined_env.yml
            - name: Get content combined yml
              run: |
                  get-content combined_env.yml.yml
            - uses: conda-incubator/setup-miniconda@v3
              with:
                  miniforge-version: 25.3.0-3
                  channels: conda-forge
                  activate-environment: ""
                  conda-remove-defaults: "true"
            - name: Setup environment
              run: |
                  get-content combined_env.yml.yml
                  ls
                  echo "LS Done"
                  mamba env create --name test_env --yes --file combined_env.yml.yml 
                  mamba run --name test_env pip install -e ./glaes --no-deps
                  mamba run --name test_env pip install -e ./geokit --no-deps
                  echo "Installation done"
                  mamba list --name test_env
                  echo "packages printed"
            - name: Run tests
              run: |
                  echo "start pytest"
                  mamba run --name test_env pytest -n auto  -vv
                  echo "Pytest done"
