on:
  push:
    branches: ["**"]


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  TestGeokitDevLocal:
    name: Test local development Version on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os:
        #   [
        #     "ubuntu-latest",
        #     "ubuntu-22.04",
        #     "macos-latest",
        #     "macos-13",
        #     "windows-latest",
        #     "windows-2022",
        #   ]
        os: ["self-hosted"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          channels: conda-forge
          activate-environment: reskit_env
          conda-remove-defaults: true
      - name: Run tests
        shell: pwsh
        run: |
          ls
          echo "LS Done"
          mamba env create --name reskit_env --yes --file requirements-dev.yml
          conda run --name reskit_env pip install . --no-deps
          echo "Installation done"
          conda list --name reskit_env
          echo "libaries printed"
          echo "start pytest"
          conda run --name reskit_env pytest -vv
          echo "Pytest done"
